% Creates a new STA for the given AP.

function staNode = createStaNode( ...
  networkSimulator, ...
  apDeviceConfig, ... % the divice configuration of the AP
  staIndex, ...       % the index of the STA
  position ...        % the position of the STA
)

staConfig = wlanDeviceConfig( ...
  Mode="STA", ...
  BandAndChannel=apDeviceConfig.BandAndChannel, ...
  ChannelBandwidth=apDeviceConfig.ChannelBandwidth, ...
  DisableRTS=true, ...
  OBSSPDThreshold=apDeviceConfig.OBSSPDThreshold ...
);
staNode = wlanNode( ...
  Name=strcat("STA ",num2str(staIndex)), ...
  Position=position, ...
  DeviceConfig=staConfig ...
);
end